#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/other                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   anidb            AniDB Popular               #
#          #   commonsense      Common Sense Selected       #
#          #   stevenlu         StevenLu's Popular Movies   #
#          #   pirated          Top 10 Pirated Movies       #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Customize summary of collection                #
#          summary_key: A collection of ...                 #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Determines collection order of the collection  #
#          collection_order_key: custom                     #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          sonarr_add_missing_key:                          #
#          # Radarr Folder to add to                        #
#          radarr_folder_key:                               #
#          # Sonarr Folder to add to                        #
#          sonarr_folder_key:                               #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "01"

templates:
  pirated:
    default:
      summary_pirated: TorrentFreak.com's Weekly Top Ten Pirated Movies
    summary: <<summary_<<key>>>>

collections:
  Based on True Story:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/based-on-or-inspired-by-a-true-story
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom
      
  Mindfuck Movies:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/mindfuck-movies
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom
      
  Outer Space Exploration:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/outer-space-space-exploration-movies
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Crazy Plot Twists:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/crazy-plot-twists
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Top Parody Movies:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/top-50-parody-movies-of-all-time
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Top Romantic Comedies:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/romantic-comedies-rotten-tomatoes-top-rated
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Best Movies on Netflix:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/best-movies-currently-on-netflix
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Best Sport Movies:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/150-best-sports-movies-of-all-time
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Best Fantasy Movies:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/best-fantasy-movies-of-all-time
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom

  Best Heist Movies:
    variables:
      key: pirated
    mdblist_list: https://mdblist.com/lists/hdlists/best-heist-movies-of-all-time
    template:
      - name: pirated
      - name: shared
        allowed_libraries: movie
      - name: arr
      - name: custom
#################################  INFO BELOW #############################
  1001 Movies You Must See Before You Die:
    trakt_list: https://trakt.tv/users/sp1ti/lists/1001-movies-you-must-see-before-you-die
    summary: "1001 Movies You Must See Before You Die is a film reference book edited by Steven Jay Schneider with original essays on each film contributed by over 70 film critics."
    url_poster: https://i.imgur.com/WmgioMY.png
    url_background: https://i.imgur.com/rVa7jiJ.jpg
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*101f"
    schedule: daily 
    
  Based on True Events:
    smart_label: originally_available.desc
    trakt_list: https://trakt.tv/users/manu101/lists/based-inspired-on-actual-events
    summary: Movies based on true events.
    sort_title: '+2 Based on true events'
  Chick Flicks:
    trakt_list: 
      - https://trakt.tv/users/29zombies/lists/romantic-comedies
      - https://trakt.tv/users/yirmaster/lists/chick-flicks
    summary: Get in touch with your feminine side.
    sort_title: '+2 Chick Flicks'
    collection_order: alpha
    collection_mode: default
  Heist Movies:
    imdb_list:
      - https://www.imdb.com/list/ls068224634/
      - https://www.imdb.com/list/ls009794682/
    summary: Movies detailing the preparation for, execution of and aftermath of a (well-)planned and often daring heist.
    sort_title: '+2 Heist'
    collection_order: alpha
    collection_mode: default
  Member Berries:
    smart_label: release.desc
    trakt_list: https://trakt.tv/users/netplexflix/lists/member-berries
    summary: Member Berry movies are movies that contain a lot of call backs or easter eggs to previous movies in the franchise or related franchises. Often franchise reboots.
    sort_title: '+2 Member Berries'
    sync_mode: sync
  Mindfuck Movies:
    smart_label: title.asc
    trakt_list: https://trakt.tv/users/benfranklin/lists/best-mindfucks
    summary: Movies that play with your mind, confuse you, and leads you on. Plot twists or surreal storylines.
    sort_title: '+2 Mindfuck'
  Quick Flicks:
    smart_label: release.desc
    summary: Movies 90 minutes or less.
    sort_title: '+2 Quick Flicks'
    collection_mode: default
    plex_search:
      duration.lte: 90
      genre.not: Animation
  Time Travel:
    smart_label: title.asc
    trakt_list: https://trakt.tv/users/vagnerr/lists/time-travel
    summary: Film/show contains time-travel. In any form. Be it time-loop, full on relocation in time, consciousness transfer...
    sort_title: '+2 Time Travel'
